spring:
  application:
    name: Alura Backend Challenge 3
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/challenge
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB